import React from 'react';
import { Document, Page, Text, View } from '@react-pdf/renderer';
import {
  styles,
  colors,
  formatReportDate,
  makeReportId,
  getRiskTier,
  safePercent,
} from './reportStyles';
import {
  PageFrame,
  ReportHeader,
  ReportFooter,
  SectionHeading,
  InfoCard,
  RiskBar,
  BulletList,
  DataTable,
  MetaBlock,
  Disclaimer,
  TierTag,
} from './ReportPrimitives';
import BrandLogo from './BrandLogo';

const DISCLAIMER =
  'This comprehensive health report is generated by Healance AI using machine-learning models and the patient\'s self-reported data. It is not a medical diagnosis. Please consult a qualified healthcare professional before making any medical decisions.';

const safe = (v, fb = 'N/A') => (v != null && v !== '' ? v : fb);

// ──────────────────────────────────────────────────────────────────
// Cover Page (shown first, summarises both reports)
// ──────────────────────────────────────────────────────────────────
const CoverPage = ({ patientName, reportId, reportDate, heart, symptoms }) => {
  const heartTier = heart ? getRiskTier(heart.results?.overallRisk) : null;
  const heartPct =
    heart && (safePercent(heart.results?.heartDiseaseRisk) ?? safePercent(heart.results?.diabetesRisk)) || 0;

  const symptomsDisease = symptoms ? safe(symptoms.predictedDisease, 'Unknown Condition') : null;
  const symptomsPct =
    symptoms && typeof symptoms.confidence === 'number' ? Math.round(symptoms.confidence * 100) : null;

  return (
    <Page size="A4" style={styles.page}>
      <PageFrame />
      <ReportHeader variant="cover" idSuffix="cover" />

      {/* Hero block with large centered logo */}
      <View style={{ alignItems: 'center', marginTop: 28, marginBottom: 24 }}>
        <BrandLogo size={64} idSuffix="cover-hero" />
        <Text
          style={{
            fontFamily: 'Helvetica-Bold',
            fontSize: 11,
            color: colors.ink,
            marginTop: 10,
            letterSpacing: 1,
          }}
        >
          HEALANCE AI
        </Text>
      </View>

      <Text
        style={[
          styles.reportTitle,
          { textAlign: 'center', fontSize: 24, marginBottom: 6 },
        ]}
      >
        Comprehensive{'\n'}Health Assessment Report
      </Text>
      <Text
        style={[
          styles.reportSubtitle,
          { textAlign: 'center', marginBottom: 28 },
        ]}
      >
        AI-powered analysis of cardiovascular, metabolic and symptom-based insights
      </Text>

      <MetaBlock
        rows={[
          { label: 'Patient', value: patientName },
          { label: 'Report ID', value: reportId },
          { label: 'Generated on', value: reportDate },
          { label: 'Generated by', value: 'Healance AI v2.4' },
        ]}
      />

      {/* Summary grid — both report types side by side */}
      <View
        style={{
          flexDirection: 'row',
          gap: 12,
          marginTop: 16,
        }}
      >
        {/* Heart & Diabetes summary tile */}
        <View
          style={{
            flex: 1,
            padding: 14,
            backgroundColor: heart ? colors.lightBg : colors.lightBgAlt,
            borderRadius: 8,
            borderWidth: 1,
            borderColor: colors.border,
          }}
          wrap={false}
        >
          <Text style={styles.infoCardHeading}>Heart & Diabetes</Text>
          {heart ? (
            <>
              <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 8 }}>
                <Text
                  style={{
                    fontFamily: 'Helvetica-Bold',
                    fontSize: 15,
                    color: heartTier.color,
                  }}
                >
                  {heartTier.label}
                </Text>
                <TierTag tier={heartTier} />
              </View>
              <Text style={styles.dataLabel}>Heart Risk</Text>
              <Text style={styles.dataValue}>
                {safePercent(heart.results?.heartDiseaseRisk) != null
                  ? `${safePercent(heart.results.heartDiseaseRisk)}%`
                  : 'N/A'}
              </Text>
              <Text style={[styles.dataLabel, { marginTop: 6 }]}>Diabetes Risk</Text>
              <Text style={styles.dataValue}>
                {safePercent(heart.results?.diabetesRisk) != null
                  ? `${safePercent(heart.results.diabetesRisk)}%`
                  : 'N/A'}
              </Text>
            </>
          ) : (
            <Text style={styles.emptyText}>No record available.</Text>
          )}
        </View>

        {/* Symptoms summary tile */}
        <View
          style={{
            flex: 1,
            padding: 14,
            backgroundColor: symptoms ? colors.lightBg : colors.lightBgAlt,
            borderRadius: 8,
            borderWidth: 1,
            borderColor: colors.border,
          }}
          wrap={false}
        >
          <Text style={styles.infoCardHeading}>Symptoms Analysis</Text>
          {symptoms ? (
            <>
              <Text
                style={{
                  fontFamily: 'Helvetica-Bold',
                  fontSize: 13,
                  color: colors.ink,
                  marginBottom: 8,
                }}
              >
                {symptomsDisease}
              </Text>
              <Text style={styles.dataLabel}>Confidence</Text>
              <Text style={styles.dataValue}>
                {symptomsPct != null ? `${symptomsPct}%` : 'N/A'}
              </Text>
              <Text style={[styles.dataLabel, { marginTop: 6 }]}>Symptoms</Text>
              <Text style={styles.dataValue}>
                {Array.isArray(symptoms.selectedSymptoms)
                  ? symptoms.selectedSymptoms.length
                  : 0}{' '}
                reported
              </Text>
            </>
          ) : (
            <Text style={styles.emptyText}>No record available.</Text>
          )}
        </View>
      </View>

      {/* What's inside */}
      <SectionHeading number="·" title="What's Inside This Report" />
      <View>
        <View style={styles.bulletItem}>
          <Text style={styles.bulletMarker}>▸</Text>
          <Text style={styles.bulletText}>
            Heart & Diabetes risk breakdown with submitted vitals, personalised diet and workout plans
          </Text>
        </View>
        <View style={styles.bulletItem}>
          <Text style={styles.bulletMarker}>▸</Text>
          <Text style={styles.bulletText}>
            Symptom-based disease prediction, precautions and recommended care plan
          </Text>
        </View>
        <View style={styles.bulletItem}>
          <Text style={styles.bulletMarker}>▸</Text>
          <Text style={styles.bulletText}>
            Medical history on file and actionable next steps
          </Text>
        </View>
      </View>

      <Disclaimer text={DISCLAIMER} />

      <ReportFooter />
    </Page>
  );
};

// ──────────────────────────────────────────────────────────────────
// Heart & Diabetes Section (1-2 pages)
// ──────────────────────────────────────────────────────────────────
const HeartSection = ({ heart, user }) => {
  const results = heart.results || {};
  const input = heart.input || {};
  const dietPlan = heart.dietPlan;
  const workoutPlan = Array.isArray(heart.workoutPlan) ? heart.workoutPlan : [];
  const overallTier = getRiskTier(results.overallRisk);
  const overallPct = safePercent(results.heartDiseaseRisk) ?? safePercent(results.diabetesRisk) ?? 0;

  const medicalConditions = Array.isArray(user.profile?.medicalConditions)
    ? user.profile.medicalConditions
    : [];
  const medications = Array.isArray(user.profile?.medications) ? user.profile.medications : [];

  const vitals = [
    { label: 'AGE', value: input.age != null ? `${input.age} yrs` : 'N/A' },
    { label: 'GENDER', value: safe(input.gender) },
    { label: 'BMI', value: input.bmi != null ? String(input.bmi) : 'N/A' },
    { label: 'BLOOD GROUP', value: safe(user.profile?.bloodGroup) },
    { label: 'HEIGHT', value: user.profile?.height != null ? `${user.profile.height} cm` : 'N/A' },
    { label: 'WEIGHT', value: user.profile?.weight != null ? `${user.profile.weight} kg` : 'N/A' },
    { label: 'BLOOD PRESSURE', value: safe(input.bloodPressure) },
    { label: 'CHOLESTEROL', value: input.cholesterol != null ? `${input.cholesterol} mg/dL` : 'N/A' },
    { label: 'BLOOD SUGAR', value: input.bloodSugar != null ? `${input.bloodSugar} mg/dL` : 'N/A' },
  ];

  const dietRows = dietPlan
    ? [
        { label: 'Breakfast', text: dietPlan.breakfast },
        { label: 'Lunch', text: dietPlan.lunch },
        { label: 'Dinner', text: dietPlan.dinner },
        { label: 'Snacks', text: dietPlan.snacks },
        { label: 'Notes', text: dietPlan.notes },
      ].filter((r) => r.text)
    : [];

  return (
    <>
      <Page size="A4" style={styles.page}>
        <PageFrame />
        <ReportHeader variant="heart" idSuffix="heart-1" />

        <Text style={styles.reportTitle}>Heart & Diabetes{'\n'}Risk Assessment</Text>
        <Text style={styles.reportSubtitle}>
          Assessment from {formatReportDate(heart.createdAt)}
        </Text>

        {/* Overall risk card */}
        <InfoCard>
          <Text style={styles.infoCardHeading}>Overall Risk Tier</Text>
          <View style={{ flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 8 }}>
            <Text style={[styles.infoCardValue, { color: overallTier.color }]}>
              {overallTier.label}
            </Text>
            <TierTag tier={overallTier} />
          </View>
          <View style={styles.riskBarTrack}>
            <View
              style={[
                styles.riskBarFill,
                {
                  width: `${Math.max(4, Math.min(100, overallPct))}%`,
                  backgroundColor: overallTier.color,
                },
              ]}
            />
          </View>
          <Text style={[styles.infoCardDesc, { marginTop: 10 }]}>
            {safe(
              results.summary,
              'Your vitals were analyzed. See detailed breakdown below.'
            )}
          </Text>
        </InfoCard>

        <SectionHeading number="01" title="Submitted Vitals" />
        <DataTable items={vitals} />

        <SectionHeading number="02" title="Risk Breakdown" />
        <RiskBar name="Heart Disease" value={results.heartDiseaseRisk} />
        <RiskBar name="Diabetes" value={results.diabetesRisk} />
        <RiskBar name="Stroke" value={results.strokeRisk} />
        <RiskBar name="Hypertension" value={results.bpRisk} />

        <SectionHeading number="03" title="Medical History Noted" />
        <View style={{ marginBottom: 6 }}>
          <Text style={styles.dataLabel}>Conditions</Text>
          {medicalConditions.length === 0 ? (
            <Text style={styles.paragraph}>None reported</Text>
          ) : (
            <BulletList items={medicalConditions} />
          )}
        </View>
        <View style={{ marginTop: 8 }}>
          <Text style={styles.dataLabel}>Current Medications</Text>
          {medications.length === 0 ? (
            <Text style={styles.paragraph}>None reported</Text>
          ) : (
            <BulletList items={medications} />
          )}
        </View>

        <ReportFooter />
      </Page>

      <Page size="A4" style={styles.page}>
        <PageFrame />
        <ReportHeader variant="heart" idSuffix="heart-2" />

        <SectionHeading number="04" title="Dietary Recommendations" />
        {dietRows.length === 0 ? (
          <Text style={styles.emptyText}>No dietary plan available.</Text>
        ) : (
          <View>
            {dietRows.map((row, idx) => (
              <View
                key={idx}
                style={[
                  styles.dietRow,
                  idx === dietRows.length - 1
                    ? { borderBottomWidth: 0, paddingBottom: 0, marginBottom: 0 }
                    : null,
                ]}
                wrap={false}
              >
                <Text style={styles.dietLabel}>{row.label}</Text>
                <Text style={styles.dietText}>{row.text}</Text>
              </View>
            ))}
          </View>
        )}

        <SectionHeading number="05" title="Weekly Workout Plan" />
        {workoutPlan.length === 0 ? (
          <Text style={styles.emptyText}>No workout plan available.</Text>
        ) : (
          <View style={styles.dataTable} wrap>
            {workoutPlan.map((w, idx) => (
              <View
                key={idx}
                style={[
                  styles.workoutRow,
                  idx === workoutPlan.length - 1 ? { borderBottomWidth: 0 } : null,
                ]}
                wrap={false}
              >
                <Text style={styles.workoutDay}>{safe(w.day, '—')}</Text>
                <Text style={styles.workoutName}>{safe(w.exercise, 'Activity')}</Text>
                <Text style={styles.workoutDuration}>{safe(w.duration, '—')}</Text>
              </View>
            ))}
          </View>
        )}

        <SectionHeading number="06" title="Next Steps & Recommendations" />
        <BulletList
          items={results.recommendations}
          emptyText="No recommendations available at this time. Continue with your current healthy routine."
        />

        <ReportFooter />
      </Page>
    </>
  );
};

// ──────────────────────────────────────────────────────────────────
// Symptoms Section (1-2 pages)
// ──────────────────────────────────────────────────────────────────
const SymptomsSection = ({ symptoms, sectionStart = 7 }) => {
  const disease = safe(symptoms.predictedDisease, 'Unknown Condition');
  const confidencePct =
    typeof symptoms.confidence === 'number' ? Math.round(symptoms.confidence * 100) : null;
  const topPredictions = Array.isArray(symptoms.topPredictions) ? symptoms.topPredictions : [];
  const reportedSymptoms = Array.isArray(symptoms.selectedSymptoms)
    ? symptoms.selectedSymptoms
    : [];
  const details = symptoms.details || {};

  const confidenceTier =
    confidencePct == null
      ? getRiskTier('low')
      : confidencePct >= 75
      ? getRiskTier('high')
      : confidencePct >= 50
      ? getRiskTier('moderate')
      : getRiskTier('low');

  const n = (offset) => String(sectionStart + offset).padStart(2, '0');

  return (
    <>
      <Page size="A4" style={styles.page}>
        <PageFrame />
        <ReportHeader variant="symptoms" idSuffix="sym-1" />

        <Text style={styles.reportTitle}>Symptom-Based{'\n'}Disease Prediction</Text>
        <Text style={styles.reportSubtitle}>
          Assessment from {formatReportDate(symptoms.createdAt)}
        </Text>

        <InfoCard>
          <Text style={styles.infoCardHeading}>Most Likely Condition</Text>
          <View style={{ flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 8 }}>
            <Text style={[styles.infoCardValue, { color: colors.ink }]}>{disease}</Text>
            <TierTag tier={confidenceTier} />
          </View>
          <View style={{ flexDirection: 'row', justifyContent: 'space-between', marginBottom: 4 }}>
            <Text style={styles.dataLabel}>Confidence</Text>
            <Text style={{ fontSize: 10, color: colors.ink, fontFamily: 'Helvetica-Bold' }}>
              {confidencePct != null ? `${confidencePct}%` : 'Not available'}
            </Text>
          </View>
          <View style={styles.riskBarTrack}>
            {confidencePct != null && (
              <View
                style={[
                  styles.riskBarFill,
                  {
                    width: `${Math.max(4, Math.min(100, confidencePct))}%`,
                    backgroundColor: colors.accent,
                  },
                ]}
              />
            )}
          </View>
        </InfoCard>

        <SectionHeading number={n(0)} title="Reported Symptoms" />
        {reportedSymptoms.length === 0 ? (
          <Text style={styles.emptyText}>No symptoms recorded.</Text>
        ) : (
          <View style={{ flexDirection: 'row', flexWrap: 'wrap' }}>
            {reportedSymptoms.map((s, idx) => (
              <View
                key={idx}
                style={{
                  width: '50%',
                  flexDirection: 'row',
                  marginBottom: 6,
                  paddingRight: 12,
                }}
              >
                <Text
                  style={{
                    fontSize: 10,
                    color: colors.riskLow,
                    marginRight: 6,
                    fontFamily: 'Helvetica-Bold',
                  }}
                >
                  ✓
                </Text>
                <Text style={{ flex: 1, fontSize: 10, color: colors.ink }}>
                  {String(s).replace(/_/g, ' ')}
                </Text>
              </View>
            ))}
          </View>
        )}

        <SectionHeading number={n(1)} title="Alternative Possibilities" />
        {topPredictions.length === 0 ? (
          <Text style={styles.emptyText}>No alternative predictions available.</Text>
        ) : (
          topPredictions.map((p, idx) => (
            <RiskBar
              key={idx}
              name={safe(p.disease, 'Unknown')}
              value={
                typeof p.confidence === 'number' ? Math.round(p.confidence * 100) : null
              }
            />
          ))
        )}

        <SectionHeading number={n(2)} title="Condition Description" />
        <Text style={styles.paragraph}>
          {safe(
            details.description,
            'No description available. Please consult a healthcare provider for more information.'
          )}
        </Text>

        <ReportFooter />
      </Page>

      <Page size="A4" style={styles.page}>
        <PageFrame />
        <ReportHeader variant="symptoms" idSuffix="sym-2" />

        <SectionHeading number={n(3)} title="Precautions" />
        <BulletList items={details.precautions} emptyText="No precautions listed." />

        <SectionHeading number={n(4)} title="Suggested Medications" />
        <BulletList
          items={details.medications}
          emptyText="No medications suggested. Please consult a physician."
        />

        <SectionHeading number={n(5)} title="Dietary Support" />
        <BulletList items={details.diets} emptyText="No dietary suggestions available." />

        <SectionHeading number={n(6)} title="Recovery Workouts" />
        <BulletList items={details.workouts} emptyText="No recovery workouts recommended." />

        <SectionHeading number={n(7)} title="Risk Factors" />
        <BulletList
          items={details.riskFactors}
          emptyText="No specific risk factors identified."
        />

        <View
          style={{
            marginTop: 16,
            padding: 12,
            backgroundColor: '#fef3c7',
            borderLeftWidth: 3,
            borderLeftColor: colors.riskModerate,
            borderRadius: 4,
          }}
          wrap={false}
        >
          <Text
            style={{
              fontFamily: 'Helvetica-Bold',
              fontSize: 9,
              color: colors.ink,
              textTransform: 'uppercase',
              letterSpacing: 0.8,
              marginBottom: 4,
            }}
          >
            Seek Medical Attention If
          </Text>
          <Text style={{ fontSize: 9, color: colors.inkSoft, lineHeight: 1.5 }}>
            Symptoms persist beyond 10 days, worsen rapidly, or you experience high fever,
            difficulty breathing, chest pain, or any other serious condition. Always consult
            a qualified physician for evaluation.
          </Text>
        </View>

        <Disclaimer text={DISCLAIMER} />

        <ReportFooter />
      </Page>
    </>
  );
};

// ──────────────────────────────────────────────────────────────────
// Main Combined Report Document
// ──────────────────────────────────────────────────────────────────
const CombinedReport = ({
  heartPrediction = null,
  symptomsPrediction = null,
  user = {},
}) => {
  const patientName = safe(user?.name, 'Patient');
  const reportId = makeReportId(
    'RPT-ALL',
    heartPrediction?._id || symptomsPrediction?._id || Date.now().toString()
  );
  const reportDate = formatReportDate(new Date().toISOString());

  // Compute section-start number for symptoms based on heart section's consumed numbers
  const symptomsSectionStart = heartPrediction ? 7 : 1;

  return (
    <Document
      title={`Healance Comprehensive Health Report — ${patientName}`}
      author="Healance AI"
      subject="Comprehensive AI Health Report"
      creator="Healance AI"
      producer="Healance AI"
    >
      {/* Cover Page */}
      <CoverPage
        patientName={patientName}
        reportId={reportId}
        reportDate={reportDate}
        heart={heartPrediction}
        symptoms={symptomsPrediction}
      />

      {/* Heart & Diabetes Section */}
      {heartPrediction && <HeartSection heart={heartPrediction} user={user} />}

      {/* Symptoms Section */}
      {symptomsPrediction && (
        <SymptomsSection
          symptoms={symptomsPrediction}
          sectionStart={symptomsSectionStart}
        />
      )}

      {/* Fallback page if no predictions at all */}
      {!heartPrediction && !symptomsPrediction && (
        <Page size="A4" style={styles.page}>
          <PageFrame />
          <ReportHeader variant="cover" idSuffix="empty" />
          <Text style={styles.reportTitle}>No Assessment Data</Text>
          <Text style={[styles.paragraph, { marginTop: 16 }]}>
            There are no saved predictions yet. Complete a health risk assessment or a
            symptom analysis from the Healance dashboard to generate a detailed report.
          </Text>
          <Disclaimer text={DISCLAIMER} />
          <ReportFooter />
        </Page>
      )}
    </Document>
  );
};

export default CombinedReport;
