import React from 'react';
import { Document, Page, Text, View } from '@react-pdf/renderer';
import {
  styles,
  colors,
  formatReportDate,
  makeReportId,
  getRiskTier,
  safePercent,
} from './reportStyles';
import {
  ReportHeader,
  ReportFooter,
  SectionHeading,
  InfoCard,
  RiskBar,
  BulletList,
  DataTable,
  MetaBlock,
  Disclaimer,
  TierTag,
} from './ReportPrimitives';

const DISCLAIMER =
  'This report is generated by Healance AI using machine-learning models based on self-reported data. It is not a medical diagnosis. Please consult a qualified healthcare professional before making any medical decisions.';

const safe = (v, fb = 'N/A') => (v != null && v !== '' ? v : fb);

const HeartDiabetesReport = ({ prediction = {}, user = {} }) => {
  const createdAt = prediction.createdAt;
  const results = prediction.results || {};
  const input = prediction.input || {};
  const dietPlan = prediction.dietPlan;
  const workoutPlan = Array.isArray(prediction.workoutPlan) ? prediction.workoutPlan : [];

  const overallTier = getRiskTier(results.overallRisk);
  const overallPct = safePercent(results.heartDiseaseRisk) ?? safePercent(results.diabetesRisk) ?? 0;

  const patientName = safe(user.name, 'Patient');
  const reportId = makeReportId('RPT-HD', prediction._id);
  const assessmentDate = formatReportDate(createdAt);

  // Collect medical history from user profile
  const medicalConditions = Array.isArray(user.profile?.medicalConditions) ? user.profile.medicalConditions : [];
  const medications = Array.isArray(user.profile?.medications) ? user.profile.medications : [];

  // Vitals table items
  const vitals = [
    { label: 'AGE', value: input.age != null ? `${input.age} yrs` : 'N/A' },
    { label: 'GENDER', value: safe(input.gender) },
    { label: 'BMI', value: input.bmi != null ? String(input.bmi) : 'N/A' },
    { label: 'BLOOD GROUP', value: safe(user.profile?.bloodGroup) },
    { label: 'HEIGHT', value: user.profile?.height != null ? `${user.profile.height} cm` : 'N/A' },
    { label: 'WEIGHT', value: user.profile?.weight != null ? `${user.profile.weight} kg` : 'N/A' },
    { label: 'BLOOD PRESSURE', value: safe(input.bloodPressure) },
    { label: 'CHOLESTEROL', value: input.cholesterol != null ? `${input.cholesterol} mg/dL` : 'N/A' },
    { label: 'BLOOD SUGAR', value: input.bloodSugar != null ? `${input.bloodSugar} mg/dL` : 'N/A' },
  ];

  return (
    <Document
      title={`Healance Heart & Diabetes Report — ${patientName}`}
      author="Healance AI"
      subject="Heart & Diabetes Risk Assessment"
      creator="Healance AI"
      producer="Healance AI"
    >
      {/* Page 1 — Cover + Executive Summary */}
      <Page size="A4" style={styles.page}>
        <ReportHeader variant="cover" />

        <Text style={styles.reportTitle}>Heart & Diabetes{'\n'}Risk Assessment Report</Text>
        <Text style={styles.reportSubtitle}>A personalized AI-driven health summary</Text>

        <MetaBlock
          rows={[
            { label: 'Patient', value: patientName },
            { label: 'Report ID', value: reportId },
            { label: 'Assessment', value: assessmentDate },
            { label: 'Generated by', value: 'Healance AI v2.4' },
          ]}
        />

        {/* Overall risk card */}
        <InfoCard>
          <Text style={styles.infoCardHeading}>Overall Risk Tier</Text>
          <View style={{ flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 8 }}>
            <Text style={[styles.infoCardValue, { color: overallTier.color }]}>
              {overallTier.label}
            </Text>
            <TierTag tier={overallTier} />
          </View>
          <View style={styles.riskBarTrack}>
            <View
              style={[
                styles.riskBarFill,
                {
                  width: `${Math.max(4, Math.min(100, overallPct))}%`,
                  backgroundColor: overallTier.color,
                },
              ]}
            />
          </View>
          <Text style={[styles.infoCardDesc, { marginTop: 10 }]}>
            {safe(results.summary, 'Your vitals were analyzed. See detailed breakdown on the following pages.')}
          </Text>
        </InfoCard>

        <SectionHeading number="01" title="Executive Summary" />
        <Text style={styles.paragraph}>
          {safe(
            results.summary,
            'Based on the submitted vitals, this report summarizes your current cardiovascular and metabolic risk profile. Review the sections that follow for detailed insights, personalized recommendations, and an actionable care plan.'
          )}
        </Text>

        <ReportFooter />
      </Page>

      {/* Page 2 — Clinical Inputs + Risk Breakdown */}
      <Page size="A4" style={styles.page}>
        <ReportHeader />

        <SectionHeading number="01" title="Submitted Vitals" />
        <DataTable items={vitals} />

        <SectionHeading number="02" title="Risk Breakdown" />
        <RiskBar name="Heart Disease" value={results.heartDiseaseRisk} />
        <RiskBar name="Diabetes" value={results.diabetesRisk} />
        <RiskBar name="Stroke" value={results.strokeRisk} />
        <RiskBar name="Hypertension" value={results.bpRisk} />

        <SectionHeading number="03" title="Medical History Noted" />
        <View style={{ marginBottom: 6 }}>
          <Text style={styles.dataLabel}>Conditions</Text>
          {medicalConditions.length === 0 ? (
            <Text style={styles.paragraph}>None reported</Text>
          ) : (
            <BulletList items={medicalConditions} />
          )}
        </View>
        <View style={{ marginTop: 8 }}>
          <Text style={styles.dataLabel}>Current Medications</Text>
          {medications.length === 0 ? (
            <Text style={styles.paragraph}>None reported</Text>
          ) : (
            <BulletList items={medications} />
          )}
        </View>

        <ReportFooter />
      </Page>

      {/* Page 3 — Personalized Plan */}
      <Page size="A4" style={styles.page}>
        <ReportHeader />

        <SectionHeading number="04" title="Dietary Recommendations" />
        {dietPlan ? (
          <View>
            {[
              { label: 'Breakfast', text: dietPlan.breakfast },
              { label: 'Lunch', text: dietPlan.lunch },
              { label: 'Dinner', text: dietPlan.dinner },
              { label: 'Snacks', text: dietPlan.snacks },
              { label: 'Notes', text: dietPlan.notes },
            ]
              .filter((row) => row.text)
              .map((row, idx, arr) => (
                <View
                  key={idx}
                  style={[
                    styles.dietRow,
                    idx === arr.length - 1 ? { borderBottomWidth: 0, paddingBottom: 0, marginBottom: 0 } : null,
                  ]}
                  wrap={false}
                >
                  <Text style={styles.dietLabel}>{row.label}</Text>
                  <Text style={styles.dietText}>{row.text}</Text>
                </View>
              ))}
            {![dietPlan.breakfast, dietPlan.lunch, dietPlan.dinner, dietPlan.snacks, dietPlan.notes].some(
              Boolean
            ) && <Text style={styles.emptyText}>No dietary plan available.</Text>}
          </View>
        ) : (
          <Text style={styles.emptyText}>No dietary plan available.</Text>
        )}

        <SectionHeading number="05" title="Weekly Workout Plan" />
        {workoutPlan.length === 0 ? (
          <Text style={styles.emptyText}>No workout plan available.</Text>
        ) : (
          <View style={[styles.dataTable]} wrap>
            {workoutPlan.map((w, idx) => (
              <View
                key={idx}
                style={[
                  styles.workoutRow,
                  idx === workoutPlan.length - 1 ? { borderBottomWidth: 0 } : null,
                ]}
                wrap={false}
              >
                <Text style={styles.workoutDay}>{safe(w.day, '—')}</Text>
                <Text style={styles.workoutName}>{safe(w.exercise, 'Activity')}</Text>
                <Text style={styles.workoutDuration}>{safe(w.duration, '—')}</Text>
              </View>
            ))}
          </View>
        )}

        <SectionHeading number="06" title="Next Steps & Recommendations" />
        <BulletList
          items={results.recommendations}
          emptyText="No recommendations available at this time. Continue with your current healthy routine."
        />

        <Disclaimer text={DISCLAIMER} />

        <ReportFooter />
      </Page>
    </Document>
  );
};

export default HeartDiabetesReport;
