import React from 'react';
import { Document, Page, Text, View } from '@react-pdf/renderer';
import {
  styles,
  colors,
  formatReportDate,
  makeReportId,
  getRiskTier,
  safePercent,
} from './reportStyles';
import {
  ReportHeader,
  ReportFooter,
  SectionHeading,
  InfoCard,
  RiskBar,
  BulletList,
  MetaBlock,
  Disclaimer,
  TierTag,
} from './ReportPrimitives';

const DISCLAIMER =
  'This prediction is AI-generated based on self-reported symptoms. It is not a medical diagnosis. Please consult a qualified healthcare professional for proper evaluation and treatment.';

const safe = (v, fb = 'N/A') => (v != null && v !== '' ? v : fb);

const SymptomsReport = ({ prediction = {}, user = {} }) => {
  const createdAt = prediction.createdAt;
  const confidenceDecimal =
    typeof prediction.confidence === 'number' ? prediction.confidence : null;
  const confidencePct = confidenceDecimal != null ? Math.round(confidenceDecimal * 100) : null;

  const disease = safe(prediction.predictedDisease, 'Unknown Condition');
  const symptoms = Array.isArray(prediction.selectedSymptoms) ? prediction.selectedSymptoms : [];
  const topPredictions = Array.isArray(prediction.topPredictions) ? prediction.topPredictions : [];
  const details = prediction.details || {};

  const patientName = safe(user.name, 'Patient');
  const reportId = makeReportId('RPT-SYM', prediction._id);
  const assessmentDate = formatReportDate(createdAt);

  // Determine tier based on confidence
  const confidenceTier =
    confidencePct == null
      ? getRiskTier('low')
      : confidencePct >= 75
      ? getRiskTier('high')
      : confidencePct >= 50
      ? getRiskTier('moderate')
      : getRiskTier('low');

  return (
    <Document
      title={`Healance Symptoms Analysis Report — ${patientName}`}
      author="Healance AI"
      subject="Symptom-based Disease Prediction"
      creator="Healance AI"
      producer="Healance AI"
    >
      {/* Page 1 — Cover + Prediction + Symptoms */}
      <Page size="A4" style={styles.page}>
        <ReportHeader variant="cover" />

        <Text style={styles.reportTitle}>Symptom-Based{'\n'}Disease Prediction Report</Text>
        <Text style={styles.reportSubtitle}>AI analysis of reported symptoms</Text>

        <MetaBlock
          rows={[
            { label: 'Patient', value: patientName },
            { label: 'Report ID', value: reportId },
            { label: 'Submitted', value: assessmentDate },
            { label: 'Generated by', value: 'Healance AI v2.4' },
          ]}
        />

        {/* Prediction card */}
        <InfoCard>
          <Text style={styles.infoCardHeading}>Most Likely Condition</Text>
          <View style={{ flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 8 }}>
            <Text style={[styles.infoCardValue, { color: colors.ink }]}>{disease}</Text>
            <TierTag tier={confidenceTier} />
          </View>
          <View style={{ flexDirection: 'row', justifyContent: 'space-between', marginBottom: 4 }}>
            <Text style={styles.dataLabel}>Confidence</Text>
            <Text style={{ fontSize: 10, color: colors.ink, fontWeight: 700 }}>
              {confidencePct != null ? `${confidencePct}%` : 'Not available'}
            </Text>
          </View>
          <View style={styles.riskBarTrack}>
            {confidencePct != null && (
              <View
                style={[
                  styles.riskBarFill,
                  {
                    width: `${Math.max(4, Math.min(100, confidencePct))}%`,
                    backgroundColor: colors.accent,
                  },
                ]}
              />
            )}
          </View>
        </InfoCard>

        <SectionHeading number="01" title="Reported Symptoms" />
        {symptoms.length === 0 ? (
          <Text style={styles.emptyText}>No symptoms recorded.</Text>
        ) : (
          <View style={{ flexDirection: 'row', flexWrap: 'wrap' }}>
            {symptoms.map((s, idx) => (
              <View
                key={idx}
                style={{
                  width: '50%',
                  flexDirection: 'row',
                  marginBottom: 6,
                  paddingRight: 12,
                }}
              >
                <Text style={{ fontSize: 10, color: colors.riskLow, marginRight: 6, fontWeight: 700 }}>
                  ✓
                </Text>
                <Text style={{ flex: 1, fontSize: 10, color: colors.ink }}>
                  {String(s).replace(/_/g, ' ')}
                </Text>
              </View>
            ))}
          </View>
        )}

        <SectionHeading number="02" title="Alternative Possibilities" />
        {topPredictions.length === 0 ? (
          <Text style={styles.emptyText}>No alternative predictions available.</Text>
        ) : (
          topPredictions.map((p, idx) => (
            <RiskBar
              key={idx}
              name={safe(p.disease, 'Unknown')}
              value={typeof p.confidence === 'number' ? Math.round(p.confidence * 100) : null}
            />
          ))
        )}

        <SectionHeading number="03" title="Condition Description" />
        <Text style={styles.paragraph}>
          {safe(
            details.description,
            'No description available. Please consult a healthcare provider for more information.'
          )}
        </Text>

        <ReportFooter />
      </Page>

      {/* Page 2 — Care Plan */}
      <Page size="A4" style={styles.page}>
        <ReportHeader />

        <SectionHeading number="04" title="Precautions" />
        <BulletList
          items={details.precautions}
          emptyText="No precautions listed."
        />

        <SectionHeading number="05" title="Suggested Medications" />
        <BulletList
          items={details.medications}
          emptyText="No medications suggested. Please consult a physician."
        />

        <SectionHeading number="06" title="Dietary Support" />
        <BulletList
          items={details.diets}
          emptyText="No dietary suggestions available."
        />

        <SectionHeading number="07" title="Recovery Workouts" />
        <BulletList
          items={details.workouts}
          emptyText="No recovery workouts recommended."
        />

        <SectionHeading number="08" title="Risk Factors" />
        <BulletList
          items={details.riskFactors}
          emptyText="No specific risk factors identified."
        />

        {/* Seek Medical Attention warning box */}
        <View
          style={{
            marginTop: 16,
            padding: 12,
            backgroundColor: '#fef3c7',
            borderLeftWidth: 3,
            borderLeftColor: colors.riskModerate,
            borderRadius: 4,
          }}
          wrap={false}
        >
          <Text
            style={{
              fontSize: 9,
              fontWeight: 700,
              color: colors.ink,
              textTransform: 'uppercase',
              letterSpacing: 0.8,
              marginBottom: 4,
            }}
          >
            ⚠ Seek Medical Attention If
          </Text>
          <Text style={{ fontSize: 9, color: colors.inkSoft, lineHeight: 1.5 }}>
            Symptoms persist beyond 10 days, worsen rapidly, or you experience high fever,
            difficulty breathing, chest pain, or any other serious condition. Always consult
            a qualified physician for evaluation.
          </Text>
        </View>

        <Disclaimer text={DISCLAIMER} />

        <ReportFooter />
      </Page>
    </Document>
  );
};

export default SymptomsReport;
